pipeline {
    agent {
            docker { image 'java:8' }
        }
    triggers {
        pollSCM('H/3 * * * *')
    }
    stages {
        stage('say hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('print java version') {
             steps {
                 sh 'java -version'
             }
         }
        stage('say goodbye') {
            steps {
                echo 'Goodbye World'
            }
        }
    }
}
